# Generated by Django 5.0.3 on 2024-03-28 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='tx_nome', max_length=100, verbose_name='Nome')),
                ('latitude', models.CharField(db_column='tx_latitude', max_length=100, verbose_name='Latitude')),
                ('longitude', models.CharField(db_column='tx_longitude', max_length=100, verbose_name='Longitude')),
                ('imagem_url', models.CharField(blank=True, db_column='tx_img_url', max_length=300, null=True, verbose_name='Imagem Url')),
            ],
            options={
                'db_table': 'tb_estados',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='nivelpoluicao',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='nivelpoluicao',
            name='nivel',
        ),
        migrations.AddField(
            model_name='nivelpoluicao',
            name='concentracao_co2',
            field=models.FloatField(db_column='nb_co2', default=12, verbose_name='Nivel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivelpoluicao',
            name='concentracao_no',
            field=models.FloatField(db_column='nb_nol', default=234, verbose_name='Nivel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivelpoluicao',
            name='concentracao_no2',
            field=models.FloatField(db_column='nb_nivel', default=234, verbose_name='Nivel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nivelpoluicao',
            name='status',
            field=models.CharField(choices=[('P', 'Pobre'), ('MP', 'Muito Pobre'), ('B', 'Bom'), ('M', 'Moderado'), ('R', 'Razoavel')], max_length=2, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='nivelpoluicao',
            name='estado',
            field=models.ForeignKey(db_column='id_estado', db_index=False, default=234, on_delete=django.db.models.deletion.CASCADE, related_name='nivelpoluicao_estado', to='core.estado', verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bairro',
        ),
    ]
